Repository PyGithub/PyGithub, pull requests merged in 2018-04, with the labels that each got.

#748 Add get_organizations()
  github/MainClass.py
  github/tests/Github_.py
  github/tests/ReplayData/Github.testGetOrganizations.txt
  github/tests/ReplayData/Github.testGetOrganizationsSince.txt
Labels: needs unit test

#664 Use 'requests' instead of 'httplib'
  github/Requester.py
  github/tests/Framework.py
  requirements.txt
  setup.py
Labels: high priority, improvement, refactoring

#533 API outside collaborators
  github/Organization.py
  github/tests/Organization.py
  github/tests/ReplayData/Organization.testGetOutsideCollaborators.txt
  github/tests/ReplayData/Organization.testOutsideCollaborators.txt
Labels: improvement

#758 Add verify option for to requests wrapper
  github/MainClass.py
  github/Requester.py
Labels: enterprise
