Repository PyGithub/PyGithub, pull requests merged in 2025-09, with the labels that each got.

#3229 Add warning about Checks API in doc-strings
  github/CheckRun.py
  github/CheckRunAnnotation.py
  github/CheckRunOutput.py
Labels: documentation

#3291 Fix GitHub breaking API change of `maintainers` in `Organization.create_team`
  github/Organization.py
  tests/Organization.py
  tests/ReplayData/Organization.testCreateTeamWithAllArguments.txt
Labels: bugfix

#3369 Update autodoc defaults
  doc/conf.py
  doc/utilities.rst
  github/GitRelease.py
  github/GithubIntegration.py
  github/IssueComment.py
  github/MainClass.py
  github/PullRequest.py
  github/Repository.py
Labels: :star: top pull request
