Repository PyGithub/PyGithub, pull requests merged in 2025-02, with the labels that each got.

#3104 Support updating pull request draft status
  github/PullRequest.py
  tests/PullRequest.py
  tests/ReplayData/PullRequest.testConvertToDraft.txt
  tests/ReplayData/PullRequest.testMarkReadyForReview.txt
Labels: GraphQL

#3171 Make `conclusion` nullable in `WorkflowJob.py`
  github/WorkflowJob.py
Labels: :star: top pull request

#2936 Link Commit to correct upstream documentation
  github/Commit.py
Labels: :star: top pull request

#3204 Refactor search results into separate classes
  github/Commit.py
  github/ContentFile.py
  github/Issue.py
  github/MainClass.py
  github/NamedUser.py
  github/Repository.py
  tests/Commit.py
  tests/ContentFile.py
  tests/Issue.py
  tests/NamedUser.py
Labels: improvement, OpenAPI

#3206 Add schema to `TimingData`
  github/WorkflowRun.py
Labels: OpenAPI

#3207 Add `OrganizationInvitation`
  github/NamedUser.py
  github/Organization.py
  github/Team.py
  tests/NamedUser.py
  tests/Organization2072.py
  tests/ReplayData/OrganizationInvitation.setUp.txt
  tests/ReplayData/OrganizationInvitation.testCancel.txt
Labels: improvement, OpenAPI

#3202 Remove error schemas from classes
  github/GitRelease.py
  github/ProjectCard.py
Labels: OpenAPI

#3209 Add and apply missing schemas
  github/AuthenticatedUser.py
  github/CodeSecurityConfig.py
  github/CopilotSeat.py
  github/DefaultCodeSecurityConfig.py
  github/GitCommitVerification.py
  github/NamedUser.py
  github/Organization.py
  github/Permissions.py
  github/RepoCodeSecurityConfig.py
  github/Repository.py
  github/Team.py
  tests/GitCommitVerification.py
Labels: improvement, OpenAPI

#3216 Sync `ProjectColumn` and `ProjectCard` tests with OpenAPI spec
  github/MainClass.py
  github/Project.py
  github/ProjectCard.py
  github/ProjectColumn.py
  tests/ProjectCard.py
  tests/ProjectColumn.py
Labels: improvement, OpenAPI

#3212 Mention removal of `AppAuth.private_key` in changelog
  doc/changes.rst
Labels: documentation

#3211 Fix broken pickle support for `Auth` classes
  github/Auth.py
  tests/Pickle.py
Labels: bugfix

#3220 Remove wrong schema from Repository
  github/Repository.py
Labels: maintenance, OpenAPI

#3221 Rename `HookDeliveryRequest` and `…Response` private headers fields
  github/HookDelivery.py
Labels: maintenance

#3223 Remove schema from `Deployment`, remove `message` attribute
  github/Deployment.py
  tests/Deployment.py
Labels: bugfix

#3225 Fix incorrect deprecated import
  github/CheckRun.py
Labels: bugfix

#3226 Make `GitTag.verification` return `GitCommitVerification`
  doc/changes.rst
  github/GitTag.py
  tests/GitTag.py
Labels: bugfix, breaking

#3219 Add `CodeSecurityConfigRepository` returned by `get_repos_for_code_security_config`
  github/CodeSecurityConfigRepository.py
  github/Organization.py
Labels: bugfix

#3235 Fix `Branch.get_required_status_checks` return type
  github/Branch.py
  github/RequiredStatusChecks.py
Labels: bugfix, OpenAPI

#3231 Sort classes' functions
  github/ApplicationOAuth.py
  github/Copilot.py
  github/Enterprise.py
  github/GithubObject.py
  github/Installation.py
  github/MergedUpstream.py
  github/OrganizationCustomProperty.py
Labels: maintenance

#3232 Sync `CopilotSeat` class with API spec
  github/CopilotSeat.py
  github/Organization.py
  tests/Copilot.py
  tests/ReplayData/Copilot.testAttributes.txt
Labels: improvement, OpenAPI

#3233 Sync `HookDeliverySummary` class with API spec
  github/HookDelivery.py
  tests/Github_.py
  tests/ReplayData/Github.testGetHookDeliveries.txt
  tests/ReplayData/Github.testGetHookDelivery.txt
Labels: improvement, OpenAPI

#3234 Sync `RequiredPullRequestReviews` class with API spec
  doc/changes.rst
  github/RequiredPullRequestReviews.py
  tests/Branch.py
  tests/ReplayData/RequiredPullRequestReviews.testOrganizationOwnedTeam.txt
  tests/RequiredPullRequestReviews.py
Labels: improvement, OpenAPI

#3236 Sync `RequiredStatusChecks` class with API spec
  github/RequiredStatusChecks.py
  tests/Branch.py
  tests/ReplayData/RequiredStatusChecks.setUp.txt
  tests/RequiredStatusChecks.py
Labels: improvement, OpenAPI

#3237 Sync `Team` class with API spec
  github/Team.py
  tests/Team.py
Labels: enterprise, improvement, OpenAPI

#3241 Move all Python files to future annotations
  github/AppAuthentication.py
  github/Auth.py
  github/AuthorizationApplication.py
  github/Autolink.py
  github/CVSS.py
  github/CWE.py
  github/CheckRunOutput.py
  github/CodeScanAlertInstanceLocation.py
  github/CodeScanTool.py
  github/CommitStats.py
  github/Consts.py
  github/Enterprise.py
  github/EnterpriseConsumedLicenses.py
  github/EnvironmentDeploymentBranchPolicy.py
  github/File.py
  github/GistFile.py
  github/GitAuthor.py
  github/GitObject.py
  github/GitTreeElement.py
  github/GithubException.py
  github/GithubRetry.py
  github/GitignoreTemplate.py
  github/HookResponse.py
  github/MergedUpstream.py
  github/NamedEnterpriseUser.py
  github/NotificationSubject.py
  github/OrganizationSecret.py
  github/OrganizationVariable.py
  github/PaginatedList.py
  github/Path.py
  github/Permissions.py
  github/Plan.py
  github/PullRequestMergeStatus.py
  github/Rate.py
  github/Referrer.py
  github/Requester.py
  github/Secret.py
  github/SecurityAndAnalysisFeature.py
  github/StatsCommitActivity.py
  github/StatsPunchCard.py
  github/WorkflowStep.py
  tests/Framework.py
  tests/GraphQl.py
Labels: maintenance

#3240 Fix return type of `PaginatedList[int]`
  github/PaginatedList.py
Labels: maintenance

#3244 Sync with OpenAPI spec
  github/CommitComment.py
  github/CommitStatus.py
  github/DependabotAlert.py
  github/Deployment.py
  github/DeploymentStatus.py
  github/Gist.py
  github/GistComment.py
  github/GistHistoryState.py
  github/GitReleaseAsset.py
  github/GithubApp.py
  github/Invitation.py
  github/Issue.py
  github/IssueComment.py
  github/IssueEvent.py
  github/Migration.py
  github/Project.py
  github/PullRequest.py
  github/StatsContributor.py
  tests/Artifact.py
  tests/Autolink.py
  tests/Event.py
  tests/Notification.py
  tests/Permissions.py
  tests/Topic.py
Labels: maintenance
