Repository PyGithub/PyGithub, pull requests merged in 2025-04, with the labels that each got.

#3267 Enhance PyGithub webhook documentation
  doc/examples/Webhook.rst
Labels: documentation

#3274 fix(CodeScanAlert): add missing attributes
  github/CodeScanAlert.py
Labels: :star: top pull request

#3277 Create codeql.yml
  .github/workflows/codeql.yml
Labels: maintenance
