Repository PyGithub/PyGithub, pull requests merged in 2025-07, with the labels that each got.

#3246 Adding `prevent_self_review` property to `Repository.createEnvironment`
  github/EnvironmentProtectionRule.py
  github/Repository.py
  tests/Environment.py
  tests/ReplayData/Environment.testCreateEnvironment.txt
  tests/ReplayData/Environment.testEnvironmentSecret.txt
  tests/ReplayData/Environment.testEnvironmentSecrets.txt
  tests/ReplayData/Environment.testEnvironmentVariable.txt
  tests/ReplayData/Environment.testEnvironmentVariables.txt
  tests/ReplayData/Environment.testUpdateEnvironment.txt
Labels: improvement

#3259 Add `PullRequest.get_issue_timeline` method
  github/PullRequest.py
  tests/PullRequest.py
  tests/ReplayData/PullRequest.testGetIssueTimeline.txt
Labels: improvement

#3260 Support built-in `reversed()` on `PaginatedList`
  github/PaginatedList.py
  tests/Framework.py
  tests/PaginatedList.py
Labels: improvement

#3299 Relax 404 condition in `Requester` exception handling
  github/Requester.py
  tests/PullRequest.py
  tests/Repository.py
  tests/Requester.py
Labels: improvement

#3313 Fix side-effect when removing Authorization key from headers
  github/Requester.py
Labels: bugfix

#3258 Add support for Sub-Issues
  github/Consts.py
  github/Issue.py
  tests/ReplayData/SubIssue.setUp.txt
  tests/ReplayData/SubIssue.testAddSubIssue.txt
  tests/ReplayData/SubIssue.testListSubIssues.txt
  tests/ReplayData/SubIssue.testPrioritizeSubIssue.txt
  tests/ReplayData/SubIssue.testRemoveSubIssue.txt
  tests/SubIssue.py
Labels: feature
