Repository PyGithub/PyGithub, pull requests merged in 2025-08, with the labels that each got.

#3318 Add suggest and create method feature to OpenAPI script
  .github/workflows/ci.yml
  scripts/openapi-update-classes.sh
  scripts/openapi.py
Labels: maintenance, OpenAPI

#3224 Return more union classe like `NamedUser | Organization | Enterprise`
  github/CommitComment.py
  github/CommitStatus.py
  github/DependabotAlert.py
  github/Deployment.py
  github/EnvironmentProtectionRuleReviewer.py
  github/GithubApp.py
  github/GithubObject.py
  github/Installation.py
  github/Invitation.py
  github/IssueComment.py
  github/IssueEvent.py
  github/Migration.py
  github/Project.py
  github/StatsContributor.py
  tests/GithubApp.py
Labels: improvement, breaking

#3341 Fix CI OpenApi apply command
  .github/workflows/ci.yml
Labels: ci, maintenance, OpenAPI

#3347 Improve OpenAPI CI
  .github/workflows/ci.yml
  .github/workflows/openapi.yml
  scripts/openapi-update-classes.sh
  scripts/openapi.py
Labels: maintenance, OpenAPI

#3329 Rework redirection URL allowance check
  github/Requester.py
  tests/Requester.py
Labels: bugfix, :star: top pull request

#3275 Point deprecation warnings to the caller code rather than inner class
  github/GithubIntegration.py
  github/MainClass.py
Labels: improvement

#3357 Add `github_actions` label to Maintenance section
  .github/release.yml
Labels: maintenance
